version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nextcloud:/var/www/html/data
      - config:/var/www/html/config
    environment:
      - PHP_MEMORY_LIMIT=1024M
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost:8080 192.168.1.87:8080
    depends_on:
      - db

  cron:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nextcloud:/var/www/html/data
      - config:/var/www/html/config
    environment:
      - PHP_MEMORY_LIMIT=1024M
    entrypoint: >
      /bin/sh -c "while true; do su -s /bin/sh -c 'php -f /var/www/html/cron.php &' www-data; sleep 300; done"
    depends_on:
      - app

volumes:
  db:
  config:
  nextcloud: